version: '3.8'

services:
  api:
    container_name: nest_rbac_api
    build: .
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "npm install &&
             npx prisma generate &&
             npx prisma migrate deploy &&
             npm run start:dev"

  db:
    container_name: nest_rbac_db
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_rbac
    volumes:
      - pgdata:/var/lib/postgresql/data

  studio:
    container_name: prisma_studio
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5555:5555"
    command: >
      sh -c "npm install &&
             npx prisma generate &&
             npx prisma studio --port 5555 --browser none"

volumes:
  pgdata:
